spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
#    设置成建表默认引擎是DB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  限制最大文件和最大请求
  servlet:
    multipart:
      max-file-size: 3Mb
      max-request-size: 3MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  file:
    urlPath:
  # JavaMailSender 邮件发送的配置
  mail:
    host: smtp.qq.com
    username: long-txgc@foxmail.com
    password: jkdlisumwejfbdef
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    port: 465
    api-path: http://39.97.102.59:8080/qi_back_end
    active-success: https://94k0pl.coding-pages.com/#/activate-success
    active-failded: https://94k0pl.coding-pages.com/#/activate-failed
  front-end:
    logUrl: https://94k0pl.coding-pages.com/#/login