# 文件上传路径
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dish?serverTimezone=UTC
    username: root
    password: du123123
  file:
    filePath: E://Summer/ucai_back_end/test/localImages/
#前端地址
    urlPath:  E://Summer/ucai_back_end/test/urlImages/